import { Metadata } from "next";
import "./globals.css";

import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Gateway Tax App",
  description: "Generated by Gateway Tax App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;600;700;800;900&family=Roboto:wght@400;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        />
        <link rel="stylesheet" href="assets/css/libraries.css" />
        <link rel="stylesheet" href="assets/css/style.css" />
      </head>

      <body>
        <div className="wrapper">
          {/* <div className="preloader">
            <div className="sk-cube-grid">
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
              <span className="sk-cube"></span>
            </div>
          </div> */}
          <Header />
          {children}
          <Footer />
        </div>
        {/* <ScriptLoader />
         */}
        <Script
          src="/assets/js/jquery-3.5.1.min.js"
          strategy="afterInteractive"
        />
        <Script src="/assets/js/plugins.js" strategy="afterInteractive" />
        <Script src="/assets/js/main.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
