export const services = [
  {
    id: 1,
    icon: "icon-server",
    title: "IT Management <br /> Services",
    desc: "IT management service that manages and oversees the IT infrastructure of any civil organization responsible for network and operations which includes data",
    listItems: [
      "Business IT alignment",
      "IT financial management",
      "IT service management",
    ],
    link: "it-solutions-single.html",
  },
  {
    id: 2,
    icon: "icon-cyberspace",
    title: "Cyber Security <br /> Services",
    desc: "Drive your business and manage risk with a global industry leader in cybersecurity, cloud, and managed security services and extend your team with leading experts.",
    listItems: ["Internet security", "Automotive security", "Cyberwarfare"],
    link: "it-solutions-single.html",
  },
  {
    id: 3,
    icon: "icon-cloud-computing",
    title: "Cloud Computing <br /> Services",
    desc: "Cloud computing is on-demand availability of computer system resources, especially data storage computing power, without direct active management by the user.",
    listItems: [
      "Private cloud services",
      "Public cloud services",
      "Hybrid cloud services",
    ],
    link: "it-solutions-single.html",
  },
  {
    id: 4,
    icon: "icon-permission",
    title: "IT Consulting <br /> Services",
    desc: "Trying to solve all your IT challenges internally can become costly and a major distraction, Leveraging knowledgeable IT consulting firms like ushelps business.",
    listItems: [
      "Scoping & planning",
      "Process & system design",
      "Project management support",
    ],
    link: "it-solutions-single.html",
  },
  {
    id: 5,
    icon: "icon-code",
    title: "Software Dev <br /> Services",
    desc: "With shorter product cycles, innovation, and mergers contributing to constant change, you are faced making business decisions every day to advance.",
    listItems: [
      "Implementation",
      "Testing & documenting",
      "Deployment & maintenance",
    ],
    link: "it-solutions-single.html",
  },
  {
    id: 6,
    icon: "icon-internet",
    title: "Backup & Recovery <br /> Services",
    desc: "While you can't predict unexpected events, we'll ensure the right precautions are in place to minimize downtime and keep you moving in the right direction.",
    listItems: [
      "Compression & Deduplication",
      "Duplication & Encryption",
      "Multiplexing & Refactoring",
    ],
    link: "it-solutions-single.html",
  },
];
